### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by doublex** [olokelo/jxlpy#1]
Even if alpha - could you add this package to `pypi.org`?

**Comment by olokelo** [comment]
Yes, I could.
It was in my plans originally but I decided not to do it yet because of current alpha stage of this project.
I would probably need to configure the build environment in order to publish wheels.
Anyway I will do that as soon as I can, so maybe later this week :)

**Comment by styler00dollar** [comment]
Please create a pip package. I spent hours trying to compile this and I still can't figure out how to do so due to random errors.

**Comment by olokelo** [comment]
Took me a while but finally it's [done](https://pypi.org/project/jxlpy) :)

For now wheels are available only for Linux distros but if someone wanted to have wheels also on a different platform, we could figure it out.

Also, I would really appreciate testing this new wheels.

**Comment by styler00dollar** [comment]
Some quick testing inside Manjaro shows that the pillow plugin is indeed functional and working. Only tried to read and write simple RGB images with different quality/effort and lossless write. Thanks.
