### ISSUE TITLE
Request to support installing from pypi for python3.11

### ISSUE THREAD

**Issue by URenko** [olokelo/jxlpy#16]
Python 3.11 has been released last year, I tested jxlpy (install from github) works well.
But I cannot install it from pypi as there is no wheel (built distribution) for python3.11 and the source distrubution (.tar.gz) seems not work.
Please consider publish a wheel for python3.11.

**Comment by olokelo** [comment]
New release [0.9.3](https://github.com/olokelo/jxlpy/releases/tag/0.9.3) has support for Python up to 3.12.
