### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by EugeneVert** [olokelo/jxlpy#17]
Please make a new release, as the current version does not contain important fixes, such https://github.com/olokelo/jxlpy/commit/b5457c8537aad105e0f12081aa10b5317f0088fb and https://github.com/olokelo/jxlpy/commit/6df0993206588efe94008ce3cf770438ee3c5674

**Comment by olokelo** [comment]
[Done](https://github.com/olokelo/jxlpy/releases/tag/0.9.3).
