### ISSUE TITLE
0.9.3 PIL decoder falis to load image

### ISSUE THREAD

**Issue by cmahnke** [olokelo/jxlpy#21]
@olokelo thanks for your quick response and the release, but there seem to be an issue with it, the PIL integration

```
Traceback (most recent call last):
  File "/home/runner/work/labs.projektemacher.org/labs.projektemacher.org/./scripts/./image-splitter.py", line 146, in <module>
    im = Image.open(args.image)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/runner/work/labs.projektemacher.org/labs.projektemacher.org/content/future/3d/jaffa/front.jxl'
```

The code is unchanged, only the dependency has been upgraded

**Comment by olokelo** [comment]
Thanks for reporting the issue. I've tested Pillow before release and it was working.
Could you please verify if you're able to open this image with using `jxlpy.JXLPyDecoder`?

I wrote a quick snippet of code and it seems to be working. You can also test it on your end.
```python
from PIL import Image
from jxlpy import JXLImagePlugin
from io import BytesIO
import requests
import jxlpy

print("jxlpy: {}, libjxl: {}".format(jxlpy.__version__, jxlpy._jxl_version))

r = requests.get("https://jpegxl.info/logo.jxl")

bio = BytesIO(r.content)
bio.seek(0)
im = Image.open(bio)
print(im.size, im.mode)
```

Gives:
```
jxlpy: 0.9.3, libjxl: 0.9.1
(1000, 1000) RGB
```

**Comment by cmahnke** [comment]
Thanks for the hint, I've used your snippet do debug the issue. Turned out that I had `pillow` pinned to an old version. It's fixed now. Tomorrow I'll test building on MacOS ARM, maybe I'll need your help again.
