### ISSUE TITLE
Does not build on ARM CPU

### ISSUE THREAD

**Issue by rphlo** [olokelo/jxlpy#25]
Trying to install it on ARM CPU (M1 Mac mini)
Fails both inside docker build (python-slim image) or on MacOS

```
error: subprocess-exited-with-error

  × Building wheel for jxlpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12.6-arm64-cpython-311
      creating build/lib.macosx-12.6-arm64-cpython-311/jxlpy
      copying jxlpy/JXLImagePlugin.py -> build/lib.macosx-12.6-arm64-cpython-311/jxlpy
      copying jxlpy/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/jxlpy
      running egg_info
      writing jxlpy.egg-info/PKG-INFO
      writing dependency_links to jxlpy.egg-info/dependency_links.txt
      writing requirements to jxlpy.egg-info/requires.txt
      writing top-level names to jxlpy.egg-info/top_level.txt
      reading manifest file 'jxlpy.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'jxlpy.egg-info/SOURCES.txt'
      running build_ext
      building '_jxlpy' extension
      creating build/temp.macosx-12.6-arm64-cpython-311
      creating build/temp.macosx-12.6-arm64-cpython-311/_jxlpy
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/rphlo/.pyenv/versions/3.11.0/include/python3.11 -c _jxlpy/_jxl.cpp -o build/temp.macosx-12.6-arm64-cpython-311/_jxlpy/_jxl.o -O2
      _jxlpy/_jxl.cpp:1240:10: fatal error: 'jxl/types.h' file not found
      #include "jxl/types.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jxlpy
ERROR: Could not build wheels for jxlpy, which is required to install pyproject.toml-based projects
```

**Comment by olokelo** [comment]
Looking at error message you got I suspect you might not have libjxl development headers installed on your system. They're needed to build since jxlpy interfaces with libjxl. Could you please try installing libjxl package or alternatively compiling libjxl from source?

**Comment by olokelo** [comment]
What image are you using for your container?

I suspect it's installing an older version of libjxl. 
API definitions included in jxlpy are updated for libjxl >=0.9.0. There was an API change in `JxlDecoderGetColorAsICCProfile` introduced in 0.9.0.
[old definition](https://github.com/libjxl/libjxl/blob/954b460768c08a147abf47689ad69b0e7beff65e/lib/include/jxl/decode.h#L779)
[new one](https://github.com/libjxl/libjxl/blob/v0.9.x/lib/include/jxl/decode.h#L750)

You may try building libjxl yourself in the container. Also Alpine edge is shipping with libjxl 0.9.1 which would probably work although I can't recommend using it for anything other than testing.

**Comment by olokelo** [comment]
Debian bookworm ships with libjxl 0.7.0. There're no jxlpy prebuilt wheels for arm architecture yet so that's probably why you need to build it from source.
Could you try building and installing more recent libjxl version in docker container/macos host and then try to install jxlpy?
You can look at official libjxl [instructions](https://github.com/libjxl/libjxl/blob/main/BUILDING.md) and also at this repo's [workflows](https://github.com/olokelo/jxlpy/blob/master/.github/workflows/packaging.yml).

**Comment by yoonthegoon** [comment]
still having this issue on M2 mac.

- install libjxl with `brew install jpeg-xl`
- `cjxl --version` or `djxl --version` is `djxl v0.10.3 0.10.3 [NEON]`
- `types.h` in `ls /op/homebrew/include/jxl/`
- `pip install jxlpy` or `pip install git+https://github.com/olokelo/jxlpy`

```
Collecting jxlpy
  Using cached jxlpy-0.9.5.tar.gz (107 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython (from jxlpy)
  Using cached Cython-3.0.11-py2.py3-none-any.whl.metadata (3.2 kB)
Using cached Cython-3.0.11-py2.py3-none-any.whl (1.2 MB)
Building wheels for collected packages: jxlpy
  Building wheel for jxlpy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for jxlpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-arm64-cpython-312
      creating build/lib.macosx-14.0-arm64-cpython-312/jxlpy
      copying jxlpy/JXLImagePlugin.py -> build/lib.macosx-14.0-arm64-cpython-312/jxlpy
      copying jxlpy/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/jxlpy
      running egg_info
      writing jxlpy.egg-info/PKG-INFO
      writing dependency_links to jxlpy.egg-info/dependency_links.txt
      writing requirements to jxlpy.egg-info/requires.txt
      writing top-level names to jxlpy.egg-info/top_level.txt
      reading manifest file 'jxlpy.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'jxlpy.egg-info/SOURCES.txt'
      running build_ext
      building '_jxlpy' extension
      creating build/temp.macosx-14.0-arm64-cpython-312
      creating build/temp.macosx-14.0-arm64-cpython-312/_jxlpy
      clang++ -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/yunis/dev/github.com/yoonthegoon/Pillow/.venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c _jxlpy/_jxl.cpp -o build/temp.macosx-14.0-arm64-cpython-312/_jxlpy/_jxl.o -O2
      _jxlpy/_jxl.cpp:1275:10: fatal error: 'jxl/types.h' file not found
       1275 | #include "jxl/types.h"
            |          ^~~~~~~~~~~~~
      1 error generated.
      error: command '/opt/homebrew/opt/llvm/bin/clang++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jxlpy
Failed to build jxlpy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (jxlpy)
```

**Comment by C0rn3j** [comment]
@olokelo please reopen this.

Maybe adding `/opt/homebrew/include` as an include dir would do the trick?

https://github.com/olokelo/jxlpy/blob/c610bde64ca6b8d075b8c7602c14b2a32d49704d/setup.py#L13

EDIT: Kinda, got it compiling:

```bash
brew install jpeg-xl
export CXXFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
pip install jxlpy
```

**Comment by joneavila** [comment]
> [@olokelo](https://github.com/olokelo) please reopen this.
> 
> Maybe adding `/opt/homebrew/include` as an include dir would do the trick?
> 
> [jxlpy/setup.py](https://github.com/olokelo/jxlpy/blob/c610bde64ca6b8d075b8c7602c14b2a32d49704d/setup.py#L13)
> 
> Line 13 in [c610bde](/olokelo/jxlpy/commit/c610bde64ca6b8d075b8c7602c14b2a32d49704d)
> 
>  include_dirs=[], 
> EDIT: Kinda, got it compiling:
> 
> brew install jpeg-xl
> export CXXFLAGS="-I/opt/homebrew/include"
> export LDFLAGS="-L/opt/homebrew/lib"
> pip install jxlpy

Thank you. I was able to install `jlxpy` on my macOS 15.3 M2 Max machine.
