### ISSUE TITLE
Mac OS wheel is version dependend

### ISSUE THREAD

**Issue by cmahnke** [olokelo/jxlpy#32]
It seems that updating to `libjxl` 0.11 broke the python module. The loader is still looking for the old version. Maybe it's possible to include a static binary instead of trying to load a system library?

```
ImportError: dlopen(/opt/homebrew/anaconda3/lib/python3.12/site-packages/_jxlpy.cpython-312-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/jpeg-xl/lib/libjxl.0.10.dylib
  Referenced from: <4B78D674-E888-3039-B154-8A252E397E57> /opt/homebrew/anaconda3/lib/python3.12/site-packages/_jxlpy.cpython-312-darwin.so
  Reason: tried: '/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.10.dylib' (no such file), '/opt/homebrew/opt/jpeg-xl/lib/libjxl.0.10.dylib' (no such file), '/opt/homebrew/Cellar/jpeg-xl/0.11.0_1/lib/libjxl.0.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/jpeg-xl/0.11.0_1/lib/libjxl.0.10.dylib' (no such file), '/opt/homebrew/Cellar/jpeg-xl/0.11.0_1/lib/libjxl.0.10.dylib'
```

**Comment by corrosive4354** [comment]
If possible, consider using statically compiled binaries instead of relying on system libraries. This usually requires configuration at build time, depending on the libraries and modules you use.

In addition, seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com), which is more professional and easy to use on Mac than docker and homebrew

**Comment by cmahnke** [comment]
Adding it statically would remove the need for additional dependencies, at least if there is a wheel available. That would certainly reduce the support requests on this.

I haven't looked into the affords to include JXL support in PIL for around two months, but maybe there a similar solution might be beneficial as well.

Never heard of Servbay, I'm not sure if it fits my needs: I develop things on Mac and deploy on Linux so the toolchain needs to bee working on both and Python doesn't seem to be mentioned at all.

**Comment by cmahnke** [comment]
Well this is certainly a bogus report, it's not a bug of this module but `brew` packaging seems to have changed. I'll close this and add a short description of my solution in case anyone else has a similar issue:

I'm not sure if this might be related to the updated to Mac OS Sequoia but the base location of the JXL libraries (and includes) has changed to `/opt/homebrew/opt/jpeg-xl/` (from `/opt/homebrew/`) 
Reinstalling the module from source is thus done by just passing the new location:
```
LDFLAGS="-L/opt/homebrew/opt/jpeg-xl/lib" CPPFLAGS="-I/opt/homebrew/opt/jpeg-xl/include" pip3 install  --force-reinstall --no-binary :all: jxlpy
```

BTW: Here seems to be comment missing, there was a reply between my first and third (now second) comment.
