### ISSUE TITLE
JXLPyEncoder object has no attribute 'do_cleanup'

### ISSUE THREAD

**Issue by alexjc** [olokelo/jxlpy#4]
Installed from the main branch on Ubuntu 20.04 a few minutes ago, everything builds perfectly.  The `verify_installed.py` script works but the encoding examples don't run.

The following exception is thrown for `encode_simple.py`:
```
Traceback (most recent call last):
  File "examples/encode_simple.py", line 6, in <module>
    enc = jxlpy.JXLPyEncoder(quality=100, colorspace='RGB', size=size, effort=7)
  File "_jxlpy/_jxl.pyx", line 699, in _jxlpy.JXLPyEncoder.__init__
    self.do_cleanup()
AttributeError: '_jxlpy.JXLPyEncoder' object has no attribute 'do_cleanup'
```

Adding an empty `do_cleanup()`  method doesn't seem to help.  Is something out of sync with the upstream library?

**Comment by alexjc** [comment]
I should add that `examples/decode_simple.py` seems to work fine; I get the raw bytes as expected.

**Comment by olokelo** [comment]
Oh, thanks for reporting.
The issue is probably that I've renamed function "do_cleanup" to "close".
This function should be called automatically when there's some kind of encoding error and it's responsible for destroying the encoder object.
Can you please try renaming all "do_cleanup" calls to "close" and see what happens :)

**Comment by alexjc** [comment]
Now I'm finding that `JxlEncoderSetBasicInfo` fails with status 1.  Trying to figure out why libjxl would fail, and trying to get it to print stuff out on the screen to help debug... No luck yet!

**Comment by olokelo** [comment]
Wish you good luck finding that out. Maybe it has to do something with your libjxl build.
Can you please post here version of your libjxl library? Also please verify if cjxl and djxl tools are working correctly.
As soon as I get home I'll check if I have this problem too :D

**Comment by alexjc** [comment]
`cjxl` works fine from the command line.  It's the latest from the main repository, it says:
```JPEG XL encoder v0.7.0 95cb570 [AVX2,SSE4,Scalar]```

**Comment by alexjc** [comment]
It's because of the orientation.  Are you accepting pull requests?
