### ISSUE TITLE
Latest libjxl requires JxlEncoderCloseFrames to output valid .jxl

### ISSUE THREAD

**Issue by alexjc** [olokelo/jxlpy#8]
There's a new API function in the latest libjxl that requires `JxlEncoderCloseFrames` to be called with the encoder before creating the output.  Otherwise, the encoder does not output a well-formed .jxl file, and it fails to decode without `--allow_partial_files`.

I put this call at the top of `get_output()` in the Cython file and it seems to work!

**Comment by olokelo** [comment]
Great! Thanks for reporting.
Could you open a pull request so that I can merge it?

**Comment by alexjc** [comment]
I push my changes here, work in progress: https://github.com/alexjc/jxlpy

**Comment by alexjc** [comment]
See PR #13.

**Comment by cmahnke** [comment]
@olokelo: Since #13 has been merged and consequently released, this might get closed.
